### ISSUE TITLE
InPlace to Loadable No Template

### ISSUE THREAD

**Issue by eluvs** [dnenov/pyChilizer#20]
I was testing out the 'InPlace to Loadable' tool just now and keep getting an error that says there's no template for family found. What does that mean? Before updating my plugin with the most recent changes I got a long error message that was showing me that it doesn't work. Is there something I am missing? 

<img width="263" alt="image" src="https://user-images.githubusercontent.com/34044878/216464218-ff06c866-c7a3-44f5-afd2-c58aeb791a89.png">

**Comment by jmcouffin** [comment]
@eluvs 
I got the same issue at first, then I figured out that was because I was using Revit in French and did not have any english generic model templates in the expected folder
it is looking for \Metric Generic Model.rft
in your default family template folder

**Comment by dnenov** [comment]
Thanks for the prompt you guys, @rastermadre is on the case!

**Comment by eluvs** [comment]
@rastermadre, was this fixed, so it looks for a different family template? Do I need a generic metric model template in my imperial family template folder for this tool?

**Comment by rastermadre** [comment]
hey @eluvs 
yes, this was fixed. It will look for the Generic Model template in the folder that is indicated as the default path for family templates.

![image](https://user-images.githubusercontent.com/43077096/219678543-3a5758dc-9c14-4815-8173-cead04751cb0.png)
It will now reference Imperial English template (Generic Model.rft), and several other languages. If it cannot find the template it will ask you to indicate the location. 
Let me know if this works for you.

**Comment by eluvs** [comment]
@rastermadre forgive my ignorance, but is there some special thing I need to do to see this update? I just tried it after updating pyrevit and got the same error in Revit 2022.

**Comment by rastermadre** [comment]
hey @eluvs, if the Update doesn't work, try removing the pyChilizer extension and installing it again. The build number should match the last one on github 
![image](https://user-images.githubusercontent.com/43077096/221181583-11557461-979e-42f2-81d7-1b6d6e0de70e.png)

**Comment by eluvs** [comment]
@rastermadre it's still not working for me for some reason. I tried removing and installing pyChilizer and pyRevit and it still won't work. I am testing this out in a new project in 2023 and 2022. Both won't work unless I have a metric Generic Model template file in our standard family template folder.

**Comment by rastermadre** [comment]
apologies, @eluvs , it should be working now with the latest update

**Comment by eluvs** [comment]
It worked! Thanks for the update @rastermadre
